#!/bin/sh
#
#  ___                                   ___      ____                            
# /\_ \            __                  /'___\    /\  _`\                           
# \//\ \    __  __/\_\    ____  _____ /\ \__/    \ \ \/\ \     __   __  __         
#   \ \ \  /\ \/\ \/\ \  /',__\/\ '__`\ \ ,__\    \ \ \ \ \  /'__`\/\ \/\ \        
#    \_\ \_\ \ \_\ \ \ \/\__, `\ \ \L\ \ \ \_/     \ \ \_\ \/\  __/\ \ \_/ |       
#    /\____\\ \____/\ \_\/\____/\ \ ,__/\ \_\       \ \____/\ \____\\ \___/        
#    \/____/ \/___/  \/_/\/___/  \ \ \/  \/_/        \/___/  \/____/ \/__/         
#                                 \ \_\                                            
#                                  \/_/                                            
#
# Email: luispfcanales@gmail.com
# Twitter: @luispfcanales

path=$(pwd)
routeDotfile=$path/config
routeLink=$HOME/.config

#REPOSITORY
github="https://github.com/luis16121013"
gitlab="https://gitlab.com/luispf"

#DOWNLOAD CONFIGURATIONS
git clone $github/alacrittyConfig.git $routeDotfile/alacritty
git clone $github/myConfigNvim.git $routeDotfile/nvim

git clone $gitlab/dwm-luispf.git $routeDotfile/dwm

#HOME DIRECTORY
ln -sf $path/.xinitrc $HOME/.xinitrc

#CONFIG DIRECTORY
[ -d $routeLink/alacritty ] && rm -rf $routeLink/alacritty
ln -sf $routeDotfile/alacritty $routeLink/alacritty

[ -d $routeLink/nvim ] && rm -rf $routeLink/nvim
ln -sf $routeDotfile/nvim $routeLink/nvim

