#!/bin/sh
#  _       _            __   ____              
# | |_   _(_)___ _ __  / _| |  _ \  _____   __ 
# | | | | | / __| '_ \| |_  | | | |/ _ \ \ / / 
# | | |_| | \__ \ |_) |  _| | |_| |  __/\ V /  
# |_|\__,_|_|___/ .__/|_|   |____/ \___| \_/   
#               |_|                            
#
# Email: luispfcanales@gmail.com
# Twitter: @luispfcanales

#DOWNLOADS PROGRAMS
sudo pacman -S xf86-video-nouveau --noconfirm
sudo pacman -S xorg --noconfirm
sudo pacman -S xorg-xinit --noconfirm
sudo pacman -S picom --noconfirm
sudo pacman -S base-devel --noconfirm
sudo pacman -S alsa-utils --noconfirm
sudo pacman -S alsa-plugins --noconfirm
sudo pacman -S alsa-oss --noconfirm
sudo pacman -S pulseaudio --noconfirm
sudo pacman -S pavucontrol --noconfirm
sudo pacman -S zsh --noconfirm
sudo pacman -S nodejs --noconfirm
sudo pacman -S npm --noconfirm
sudo pacman -S bspwm --noconfirm
sudo pacman -S sxhkd --noconfirm
sudo pacman -S exa --noconfirm
sudo pacman -S bat --noconfirm
sudo pacman -S alacritty --noconfirm
sudo pacman -S ksnip --noconfirm
sudo pacman -S gedit --noconfirm
sudo pacman -S nitrogen --noconfirm
sudo pacman -S pcmanfm --noconfirm
sudo pacman -S rofi --noconfirm
sudo pacman -S ttf-jetbrains-mono --noconfirm
sudo pacman -S firefox --noconfirm

if [[ -d $HOME/.config ]]; then
	./setlinks.sh
else
	mkdir $HOME/.config
	./setlinks.sh
fi

